---
remote: remote:/pub/images/{branch}/cloud
key: 0x00000000
repository_url: file:///space/ALT/{branch}
log_level: info
bad_arches:
- armh

images:
  opennebula:
    target: vm/opennebula-systemd
    kinds:
    - qcow2
    exclude_arches:
    - aarch64
  vm:
    target: vm/systemd
    kinds:
    - qcow2
    exclude_arches:
    - aarch64
    prerequisites:
    - use/net/networkd
    - use/net-ssh
    - use/vmguest/kvm
    - use/repo
  rootfs-minimal:
    target: ve/docker
    kinds:
    - tar.xz
    tests:
    - method: docker
    no_scripts:
    - var
  rootfs-systemd:
    target: ve/systemd-base
    kinds:
    - tar.xz
    tests:
    - method: lxd
    scripts:
    - securetty

branches:
  Sisyphus:
    arches:
      i586:
      x86_64:
      aarch64:
      armh:
        repository_url: file:///space/ALT/{branch}-{arch}
  p8:
    arches:
      i586:
      x86_64:
    branding: alt-starterkit
    repository_url: file:///space/ALT/{branch}

# services:
  # sshd:
    # images:
    # - opennebula
    # exclude_branches:
    # - Sisyphus
    # state: disable

# packages:
  # gosu:
    # images:
    # - rootfs-minimal
    # exclude_branches:
    # - p8

scripts:
  securetty:
    contents: |
      #!/bin/sh

      echo pts/0 >> /etc/securetty
    global: no
    number: 1
  var:
    contents: |
      #!/bin/sh

      for dir in run lock; do
          mkdir -p "/$dir"
          mv /var/"$dir"/* "/$dir"
          rmdir "/var/$dir"
          ln -sf "/$dir" /var
      done
    global: yes
    number: 27
...
