---
remote: remote:/pub/images/{branch}/cloud
key: 0x00000000
repository_url: file:///space/ALT/{branch}
log_level: info
bad_arches:
- armh

images:
  opennebula:
    target: vm/opennebula-systemd
    kinds:
    - qcow2
    exclude_arches:
    - aarch64
  rootfs-minimal:
    target: ve/docker
    kinds:
    - tar.xz
  rootfs-systemd:
    target: ve/systemd-base
    kinds:
    - tar.xz

branches:
  Sisyphus:
    arches:
      i586:
      x86_64:
      aarch64:
      armh:
        repository_url: file:///space/ALT/{branch}-{arch}
  p8:
    arches:
      i586:
      x86_64:
    branding: alt-starterkit
    repository_url: file:///space/ALT/{branch}

# services:
  # sshd:
    # images:
    # - opennebula
    # exclude_branches:
    # - Sisyphus
    # state: disable

# packages:
  # gosu:
    # images:
    # - rootfs-minimal
    # exclude_branches:
    # - p8
...
