---
remote: remote:/pub/images/{branch}/cloud
key: '0x00000000'

images:
  opennebula:
    target: vm/opennebula-systemd
    kind:
    - qcow2
    skip_arches:
    - aarch64
  rootfs-minimal:
    target: ve/docker
    kind:
    - tar.xz
  rootfs-systemd:
    target: ve/systemd-base
    kind:
    - tar.xz

branches:
    Sisyphus:
      arches:
      - i586
      - x86_64
      - aarch64
    p8:
      arches:
      - i586
      - x86_64
      branding: alt-starterkit
...
