---
remote: remote:/pub/images/{branch}/cloud
key: '0x00000000'

images:
  opennebula:
    target: vm/opennebula-systemd
    kinds:
    - qcow2
    skip_arches:
    - aarch64
  rootfs-minimal:
    target: ve/docker
    kinds:
    - tar.xz
  rootfs-systemd:
    target: ve/systemd-base
    kinds:
    - tar.xz

branches:
    Sisyphus:
      arches:
      - i586
      - x86_64
      - aarch64
    p8:
      arches:
      - i586
      - x86_64
      branding: alt-starterkit

# packages:
  # gosu:
    # images:
    # - rootfs-minimal
    # exclude_branches:
    # - p8
...
